// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebvyuyfzfmvwearozskj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVidnl1eWZ6Zm12d2Vhcm96c2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODMxNDMsImV4cCI6MjA2MjY1OTE0M30.y7h00ZkK8mk2q1E4qIe4GxeOiDCyix33Hapa5wZL_RM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);